# Generated by Django 3.1.4 on 2020-12-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_outputplot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputplot',
            name='id',
        ),
        migrations.AddField(
            model_name='outputplot',
            name='outputplot_id',
            field=models.PositiveIntegerField(db_column='id', default=-1, primary_key=True, serialize=False),
        ),
    ]
